(* ::Package:: *)

(* ::Title:: *)
(*QuantumUtils for Mathematica*)
(*M2M Unit Tests*)


(* ::Subsection::Closed:: *)
(*Copyright and License Information*)


(* ::Text:: *)
(*This package is part of QuantumUtils for Mathematica.*)
(**)
(*Copyright (c) 2015 and later, Christopher J. Wood, Christopher E. Granade, Ian N. Hincks*)
(**)
(*Redistribution and use in source and binary forms, with or withoutmodification, are permitted provided that the following conditions are met:*)
(*1. Redistributions of source code must retain the above copyright notice, this  list of conditions and the following disclaimer.*)
(*2. Redistributions in binary form must reproduce the above copyright notice,  this list of conditions and the following disclaimer in the documentation  and/or other materials provided with the distribution.*)
(*3. Neither the name of quantum-utils-mathematica nor the names of its  contributors may be used to endorse or promote products derived from  this software without specific prior written permission.*)
(**)
(*THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THEIMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AREDISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLEFOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIALDAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS ORSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVERCAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USEOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*)


(* ::Subsection:: *)
(*Preamble*)


BeginPackage["M2MTests`"];


(* ::Text:: *)
(*The following packages are needed, but their contexts should not be loaded globally.*)


Needs["QUDevTools`"];
Needs["M2M`"];


(* ::Section::Closed:: *)
(*Results*)


Begin["`UnitTests`"];


$RegisteredTests={};
$TestResults := RunTest[$RegisteredTests];


End[];


(* ::Section:: *)
(*Unit Tests*)


Begin["`UnitTests`"];


(* ::Subsection:: *)
(*Matrices and Operations*)


TestCase[$RegisteredTests, "M2M:ExpressionToMATLAB",
	And[
		ExpressionToMATLAB[a + b] == "(a+b)",
		ExpressionToMATLAB[a b] == "(a.*b)",
		ExpressionToMATLAB[a.b] == "(a*b)",
		ExpressionToMATLAB[Sin[x]] == "sin(x)",
		ExpressionToMATLAB[IdentityMatrix[3]] == "[1 0 0; 0 1 0; 0 0 1]"
	]
]


TestCase[$RegisteredTests, "M2M:SimpleFunctionToMATLAB", 
	SimpleFunctionToMATLAB["f", {x}, Sin[#]-#^2> 3&] == "% f TODO: add documentation here.\nfunction Y = f(x)\n% WARNING: This file was automatically generated by the M2M package for Mathematica.\n%          Do not edit the following lines directly.\nY = (((-1.*(x.^2))+sin(x))>3);\nend"	
];


TestCase[$RegisteredTests, "M2M:StatementToMATLAB",
	StatementToMATLAB[If[a > 3, b = c, c = b]] == "if (a>3)\n\tb = c;\nelse\n\tc = b;\nend"
];


TestCase[$RegisteredTests, "M2M:FunctionToMATLAB",
	With[{X = PauliMatrix[1]},
		FunctionToMATLAB["f",{x},If[Tr[x.X] < 1, x / Tr[x], 0]]
	] == "% f TODO: add documentation here.\nfunction retval = f(x)\n% WARNING: This file was automatically generated by the M2M package for Mathematica.\n%          Do not edit the following lines directly.\nif (trace((x*[0 1; 1 0]))<1)\n\tretval = (x./trace(x));\nelse\n\tretval = 0;\nend\nend"
];


(* ::Subsection::Closed:: *)
(*End*)


End[];


(* ::Section::Closed:: *)
(*End Package*)


EndPackage[];
